### PR TITLE
[WIP/Feedback] Clean up AvlTree

### PR DESCRIPTION
**Pull request by assertchris**

### CODE REVIEW

**Comment by morrisonlevi** [comment]
This one does a lot of the same stuff as PR #34. This does a few things differently, but there are a few more things you've done:

 - Replaced ternaries with `if/else`
 - Aligned variable assignments
 - Added whitespace

These things are all style type changes that do not necessarily have any merit.

Renaming the variables is a change I'd be okay with; if you push up a commit that only renames the variables I'll accept that.

**Comment by assertchris** [comment]
Seems you're not interested in pulling the style changes I'm interested in pushing. That's ok. :)

I feel like renaming variables is such a small part of what I'm trying to do that it would just depress me to only rename variables...

Thanks for taking the time to review and provide your feedback.

**Comment by morrisonlevi** [comment]
Again, I thank you for your interest. In the future I recommend changing a smaller subset and getting feedback on that, since you don't know how a given project will react to the changes.

**Comment by assertchris** [comment]
Yip. It's always a struggle to commit just a few changes, when I encounter awesome work like this.

**Comment by morrisonlevi** [comment]
What features of this library do you anticipate using?

**Comment by assertchris** [comment]
I discovered it from [this thread](https://groups.google.com/forum/#!topic/php-fig/4DoYkRkryGQ) and am most interested in the data structures it provides for implementing the algorithm stuff I've been learning recently.

**Pull request closed without merging**
