### PR TITLE
Add priority queue.

### PR DESCRIPTION
**Pull request by mcordingley**
SPL has priority queues, but they lack a key piece of functionality: the ability to decrease the key of a queue element. A fair number of uses of priority queues depend on this. One example is Djisktra's algorithm. This class is an implementation of a pairing heap, which has performance almost as good as that of a Fibonacci heap, but is considerably simpler to implement.

This class has a few notable differences from the SPL implementations:

- The queue exclusively accepts objects. The reason for this is that it uses SPLObjectStorage as a way to map inserted elements with their tree objects. An elegant method for relaxing this restriction would be a nice improvment.
- It does not implement the Iterator interface. It can if there appears to be a need, but I struggle to see the reason for it. Therefore, I'm KISSing it until proven otherwise.
- Arbitrary elements can be removed. With the pieces in place to reprioritize elements, it seemed an easy task to add what should be a useful ability.

One issue with this pull that I'm not thrilled with, but count as "good enough for now" is the test. It does its job, but is ugly and could use improvements from someone who's better at writing tests.

### CODE REVIEW

**Comment by morrisonlevi** [comment]
> The queue exclusively accepts objects. The reason for this is that it uses SPLObjectStorage as a way to map inserted elements with their tree objects. An elegant method for relaxing this restriction would be a nice improvment.

This repository has `Map` and `Set` structures that could be used instead. Is there something about those that would also make them unsuitable?

**Comment by morrisonlevi** [comment]
After looking at the implementation a bit more I think I'd prefer it if there was a helper class instead of `stdclass`. Would you be opposed to that?

**Comment by mcordingley** [comment]
Re Map and Set: I don't believe there is anything unsuitable about `Map`. I use `SplObjectStorage` to map the bound element to its tree object and to test in constant time to see if the tree contains an element or not. I believe `Map` covers these uses. It currently uses `SplObjectStorage` because I implemented this and the other structure(s) that I'm sending as PRs first in my own library. I'm sending them as pulls into yours because it's better for everyone for us to coalesce around one good library, instead of having dozens of tiny, personal libraries.

Re using a helper class: Not at all. I went with stdClass because it was used entirely internally and is simple.

**Comment by morrisonlevi** [comment]
I appreciate the help. Right now I am mildly unhappy with the way Ardent is designed. It's designed around this core `Collection` interface that does things like `map`, `filter`, etc. In the average case data structures don't need to do anything to work with these operations, but in some cases they can specialize them. What happens in general is that most classes use some trait to implement the standard behavior for each method and this is what I am unhappy with.

Also, it only provides these algorithms on `Collection`s; what about arrays or other iterators? I think I will be redesigning the library soon to have simpler data structures and provide stand-alone algorithms that work with arrays and iterators.

**Comment by morrisonlevi** [comment]
Also, I think the `PriorityQueue` should have an iterator. I can see a consumer using it as a stream of inputs – it doesn't really care that it is a priority queue. Does that make sense?

**Comment by mcordingley** [comment]
Not really. Can you elaborate on this? Why would you need to iterate over a queue other than implicitly by successive dequeue operations?

Note that the traversal order of elements in a priority queue isn't guaranteed except when using `dequeue` as priority queues are always implemented as heaps and heaps are only partially ordered. This is meant to be used like a regular queue. That is, items get enqueued as they are found and then dequeued from the front of the queue when the next element is to be processed. That a regular queue can be iterated over in order is a happy side-effect of the simpler way that they're represented, rather than a definitional part of a queue.

**Comment by mcordingley** [comment]
Incidentally, I would love for `object` to be a hintable type. It would preclude some of the repetitive checks for `is_object` within the class.

**Comment by morrisonlevi** [comment]
As I understand it you only care about `object` because `SplObjectStorage` only uses objects, right? So if you use a map provided by this library that restriction no longer applies. You would rather be able to accept any type, right?

**Comment by mcordingley** [comment]
Yes. And I looked at your implementation of `hash` a couple of hours back. I like it a lot. Didn't realize that `spl_object_hash` existed until then. Probably the simplest thing then would be to alter it to run the incoming value through that function and then use that as the key to an associative array. `Map` would probably also work, but this keeps things simpler and keeps down the interdependencies between components.

**Comment by mcordingley** [comment]
Ah, I noticed that you have things throw an exception if the user attempts to access a value and the structure is empty. The way that I've seen things like this done in the past and in the literature is for the structure to instead return `null`, which means that the user can do something like this:

    while ($element = $queue->dequeue()) {
        // Do things, possibly adding new items onto the end of the queue.
    }

I bring this up because this stucture should be in harmony with the others and I'm not convinced that having to either wrap things in a try/catch block or do more work to check the structure size before each element removal is desirable.

**Comment by morrisonlevi** [comment]
I find this latest find of yours to be quite humorous, because you know what the way to avoid the exception is? *Use the iterator!* :D

**Comment by mcordingley** [comment]
Using an iterator means that you can rewind the iteration. It's part of the interface. Proper use of a stack or queue modifies the state of the data structure as you use it. You add and remove elements during the traversal. That's the point! Otherwise, you may as well just build an array, possibly sort it, and then traverse it as needed.

**Comment by morrisonlevi** [comment]
Not all iterators are guaranteed to be rewindable. Notably generators are not rewindable, and they are built in to the language.

**Comment by mcordingley** [comment]
Huh. I think I'm going to have to think on this for a time. I'm still not entirely comfortable with the idea, but that may just be because it involves a shift in thinking.

**Comment by mcordingley** [comment]
Yeah. What you say makes sense. I'll write up an iterator for it here this week and change the queue to throw the empty exception.

**Comment by mcordingley** [comment]
So, which interfaces do you think the iterator should implement? I'm having some trouble following everything that's in there.

**Comment by morrisonlevi** [comment]
Just do normal iterator methods and add an `isEmpty()` method.

**Comment by mcordingley** [comment]
That ought to do it.

**Comment by mcordingley** [comment]
So, is this going to get merged? It's been about six months. If not, I'm going to delete my fork as part of keeping my profile tidy.

**Comment by morrisonlevi** [comment]
Sorry about that - I'll review this again tomorrow.

**Comment by morrisonlevi** [comment]
I have two requests:

  * Can you squash all the commits into one?
  * Can you split that giant test into at least one more test case?

**Comment by mcordingley** [comment]
* It looks like GitHub has a new feature to squash commits in a pull request. I just saw this when merging somebody else's pull on something else. No idea when this happened, but you should be able to squash when you merge it.
* I know that it's ugly in how large it is, but the test is meant to assert that items come out in a particular order no matter when they were inserted. I don't know how I could meaningfully break it down into something smaller.

**Comment by morrisonlevi** [comment]
To trim down the test examine behaviors one at a time:

1. Given a few insertions of normal priority inserted in priority order test that they come out as expected.
2. Insert them out of priority and check they come out as expected.
3. Build on the above tests by removing items.

**Pull request closed without merging**
