### PR TITLE
Add Pairing Heap-based priority queue.

### PR DESCRIPTION
**Pull request by mcordingley**
Continued from #45, implementing requested changes from there.

### CODE REVIEW

**Comment by mcordingley** [comment]
The code has been squashed into a single commit and the tests are broken up. I've also updated the code to your new project structure.

**Comment by morrisonlevi** [comment]
At a glance this looks better. Thank you. I'll review it again later and then probably merge.

**Comment by mcordingley** [comment]
Fantastic. Thank you.

**Comment by mcordingley** [comment]
When can you get to this? I'm still waiting to be able to delete my fork and still have one other structure to send a pull over about.

**Comment by mcordingley** [comment]
Awesome, thanks.

**Pull request merged**
