### PR TITLE
Add build status and stable version badges to readme

### PR DESCRIPTION
**Pull request by JeroenDeDauw**

### CODE REVIEW

**Comment by morrisonlevi** [comment]
Hmm. I'm not sure about the stable version badge; there does not exist a "stable" version and I have broken backwards compatibility several times since this is pre-1.0.0 software.

**Comment by JeroenDeDauw** [comment]
My bad - that wording is inaccurate. What I meant to say is "latest tagged version". The badge just shows that and does not imply anything beyond what is already implied by the tag.

**Comment by morrisonlevi** [comment]
Thank you for looking into this simple fix and sorry for taking so long. I have decided that for now these are not necessary.

**Comment by JeroenDeDauw** [comment]
It's nice to be able to quickly see if a project has a running and passing build. However, your project :)

**Comment by morrisonlevi** [comment]
:D I understand. Just for reference though it has been a long time since the tests failed. If you changed it to just build (no stable badge) I would accept.

**Pull request closed without merging**
